# Generated by Django 5.1.6 on 2025-02-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('baseinfo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_count', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('business_profile_count', models.IntegerField()),
                ('offer_count', models.IntegerField()),
            ],
        ),
    ]
