# Generated by Django 5.1.6 on 2025-02-07 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='germany', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='01515399543', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('Business', 'business'), ('Customer', 'customer')], default='business', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default='9-17', max_length=50),
            preserve_default=False,
        ),
    ]
