# Generated by Django 5.1.6 on 2025-02-11 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='min_delivery_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='min_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
