# Generated by Django 5.1.6 on 2025-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offers_min_delivery_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='min_delivery_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
