# Generated by Django 5.1.6 on 2025-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0004_alter_offers_min_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerdetails',
            name='feature',
            field=models.JSONField(default=dict),
        ),
    ]
