# Generated by Django 5.1.6 on 2025-02-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_rename_feature_offerdetails_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetails',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerdetails', to='offers_app.offers'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.ImageField(upload_to='offerimg/'),
        ),
    ]
